# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem 'mqtt'
gem 'twitter'
gem 'sad_panda'
gem 'aylien_text_api'
